# Configuration for Alacritty, the GPU enhanced terminal emulator

[window]
  dimensions = { columns = 153, lines = 50 }
  padding = { x = 5, y = 5 }
  decorations = "buttonless"
  startup_mode = "Windowed"
  opacity = 0.9

[scrolling]
  history = 5000
  multiplier = 3

# Font configuration (changes require restart)
[font]
  normal = { family = "Fisa Code" }
  bold = { family = "Fisa Code", style = "Medium" }
  italic = { family = "Fisa Code", style = "Light Italic" }
  size = 18.0

  offset = { x = 0, y = 0 }
  glyph_offset = { x = 0, y = 0 }


[shell]
program = "/bin/zsh"  # Replace with your preferred shell if different
args = ["--login", "-c", "tmux attach-session -t  || tmux new-session -s "]
  # Thin stroke font rendering (macOS only)
  # use_thin_strokes = true

# When true, bold text is drawn using the bright variant of colors.
#draw_bold_text_with_bright_colors = false

# Gruvbox dark
# [GruvboxDark]
#   primary = { background = "#282828", foreground = "#ebdbb2" }
#
#   [GruvboxDark.normal]
#     black = "#282828"
#     red = "#cc241d"
#     green = "#98971a"
#     yellow = "#d79921"
#     blue = "#458588"
#     magenta = "#b16286"
#     cyan = "#689d6a"
#     white = "#a89984"
#
#   [GruvboxDark.bright]
#     black = "#928374"
#     red = "#fb4934"
#     green = "#b8bb26"
#     yellow = "#fabd2f"
#     blue = "#83a598"
#     magenta = "#d3869b"
#     cyan = "#8ec07c"
#     white = "#ebdbb2"

# Palenight
[colors]
  primary = { background = "#292d3e", foreground = "#d0d0d0" }

  [colors.normal]
    black = "#292d3e"
    red = "#f07178"
    green = "#c3e88d"
    yellow = "#ffcb6b"
    blue = "#82aaff"
    magenta = "#c792ea"
    cyan = "#89ddff"
    white = "#d0d0d0"

  [colors.bright]
    black = "#434758"
    red = "#ff8b92"
    green = "#ddffa7"
    yellow = "#ffe585"
    blue = "#9cc4ff"
    magenta = "#e1acff"
    cyan = "#a3f7ff"
    white = "#ffffff"
