# Configuration for Alacritty, the GPU enhanced terminal emulator

window:
  dimensions:
    columns: 153
    lines: 50
  padding:
    x: 5
    y: 5
  decorations: buttonless
  startup_mode: Windowed
  opacity: 0.9
scrolling:
  history: 5000
  multiplier: 3

# Font configuration (changes require restart)
font:
  normal:
    family: "Fisa Code"
    # family: "Fira Code"
    # family: "Source Code Pro"
    # style: Retina

  # The bold font face
  bold:
    family: "Fisa Code"
    style: Medium
    # family: "Fira Code"
    # family: "Source Code Pro"

  # The italic font face
  italic:
    family: "Fisa Code"
    style: "Light Italic"
    # style: "Light Oblique"
    # family: "Fira Code"
    # family: "Source Code Pro"
    # style: "Medium Italic"

  # Point size of the font
  size: 16.0

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0

  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina you
  # probably want this set to false.
  #
  # macOS >= 10.14.x:
  #
  # If the font quality on non-retina display looks bad then set
  # `use_thin_strokes` to `true` and enable font smoothing by running the
  # following command:
  #   `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
  #
  # This is a global setting and will require a log out or restart to take
  # effect.
  # use_thin_strokes: true

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: false

### Gruvbox dark ###
GruvboxDark: &GruvboxDark # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: "#282828"
    # soft contrast: background = '0x32302f'
    foreground: "#ebdbb2"

  # Normal colors
  normal:
    black: "#282828"
    red: "#cc241d"
    green: "#98971a"
    yellow: "#d79921"
    blue: "#458588"
    magenta: "#b16286"
    cyan: "#689d6a"
    white: "#a89984"

  # Bright colors
  bright:
    black: "#928374"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#ebdbb2"

Palenight: &Palenight # Default colors
  primary:
    background: "#292d3e"
    foreground: "#d0d0d0"

  # Normal colors
  normal:
    black: "#292d3e"
    red: "#f07178"
    green: "#c3e88d"
    yellow: "#ffcb6b"
    blue: "#82aaff"
    magenta: "#c792ea"
    cyan: "#89ddff"
    white: "#d0d0d0"
  # Bright colors
  bright:
    black: "#434758"
    red: "#ff8b92"
    green: "#ddffa7"
    yellow: "#ffe585"
    blue: "#9cc4ff"
    magenta: "#e1acff"
    cyan: "#a3f7ff"
    white: "#ffffff"

colors: *Palenight
